### ISSUE TITLE
[Bug] Plan Window Can't be Dismissed on second Mac

### ISSUE THREAD

**Issue by Sherlouk** [FlineDev/ReMafoX#40] opened 2022-10-15 15:01 UTC
## Steps to Reproduce:

(Spoke to you on Twitter about this)

1. Subscribe to ReMafoX on one machine
1. Open ReMafoX on another machine
1. Restore Purchases
1. Press 'Continue using your Current Plan'
1. Notice that Apple prompts you to review subscription settings in 'Account -> View My Account -> Settings'
1. Notice how the prompt closes and you're still on the plan window

## Expected Behavior:

Given I have already subscribed, it should be possible to dismiss the plan window once the purchase has been restored.

## Current Behavior:

ReMafoX knows that you have access to a premium plan, and does grant you access. You can continue to use ReMafoX as expected with no issue. However, the plan window itself cannot be dismissed or closed (even after restarting the app).

<img width="1012" alt="Screenshot 2022-10-15 at 3 58 45 pm" src="https://user-images.githubusercontent.com/15193942/195993207-d07ff8c1-dead-4dba-8434-e828ab8e7e1b.png">

## Environment

<details>
<summary>Show environment details</summary>

- App Version: 1.0.2 (Build 51)
- System Version: 12.6 (Build 21G115)
- System CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

</details>

**Comment by Jeehut** [comment] 2022-10-15 15:41
This is clearly a bug. I just didn't test this properly, it seems and I know exactly what the issue is. I have a special "you have to choose a plan on first start" logic which disables itself once you've chosen a plan. All I need to do to fix it is to automatically disable this mode when a purchase could be successfully restored, which I clearly missed.

Will fix in next update!

**Comment by Jeehut** [comment] 2022-10-15 16:50
@Sherlouk I just implemented a fix for this. It will be included in the next update (`1.0.3`) to be released soon. 🎉

**Closed** 2022-10-15 16:49 UTC
Labels: Bug Report, Size: Small

**Comment by Jeehut** [comment] 2022-10-15 17:13
@Sherlouk Do you need Welsh (`cy`) or Welsh (United Kingdom) (`cy-GB`)? There seem to be 2 options in Xcode.

**Comment by Jeehut** [comment] 2022-10-16 08:05
Just uploaded and submitted version `1.0.3` with the fix for review. Should be available in ~24 h from now.
