### ISSUE TITLE
[Bug] When starting app, empty window

### ISSUE THREAD

**Issue by gaige** [FlineDev/RemafoX#44] opened 2022-10-15 21:30 UTC
## Steps to Reproduce:

1. Quit App
1. Launch App

## Expected Behavior:

Window should show up with standard items.  This may be related to previously-reported issue with moved app folder.

Especially after old folder was reconstituted aside prior, renamed, folder.

## Current Behavior:

<img width="1012" alt="CleanShot 2022-10-15 at 17 28 15@2x" src="https://user-images.githubusercontent.com/3351751/196008227-f9641216-cedb-453b-a366-cbbfc3410dee.png">

## Environment

<details>
<summary>Show environment details</summary>

- App Version: 1.0.2 (Build 51)
- System Version: 12.6 (Build 21G115)
- System CPU: Intel(R) Xeon(R) W-3245 CPU @ 3.20GHz

</details>

**Comment by Jeehut** [comment] 2022-10-16 05:18
Thank you for reporting this.

This is a weird window reinstation behavior that I've seen a few times during testing as well. Note that closing the window and reopening it (e.g. via Cmd + P) fixes the issue with the left part of the window not being shown. I will have a look at that soon.

The other topic, which is that no projects are shown, is a different issue though. Actually, moving a folder of a project that you set up earlier should have no influence on this list. Only after pressing the 🗑️ icon on one of the projects in this list should remove an entry from the projects list. Do I understand it correctly, that a project disappeared from this list without you ever pressing the 🗑️ icon for it? That would definitely be something I've never seen before and need to investigate.

**Comment by gaige** [comment] 2022-10-16 08:51
I seemingly can reproduce the problem at will if I rename the directory the project is in. I do see that closing the window and then re-opening the Projects Browser window does restore the left half, although I recall that not being sufficient at some point yesterday (however I could be mistaken).

This morning, if I rename the directory that the `.remafox` file is in, that seems to cause the problem on next launch.

**Comment by gaige** [comment] 2022-10-16 09:48
Let me clarify, as my reply this morning wasn't well targeted. The at-will part is getting the window to reinstantiate with just the list of projects in it and not the left part of the window.

I've not yet been able to reproduce the same with no projects visible. If that recurs, I'll let you know.

**Comment by Jeehut** [comment] 2022-10-16 16:22
Thank you for clarifying and providing additional details!

**Comment by Jeehut** [comment] 2022-11-03 05:42
I am no longer seeing this issue after upgrading to macOS Ventura. Could it be that this was a bug in SwiftUI that was fixed by now? I'm not sure, I will keep this open for now, please report this if you are on Ventura and still run into this.

**Comment by Jeehut** [comment] 2022-12-10 13:21
I can't reproduce this issue anymore, should be fixed. Closing now.
Please comment if you come across this and try to provide as much context as possible.

**Closed by Jeehut** 2022-12-10 13:21 UTC
Labels: Bug Report, Size: Small
