### ISSUE TITLE
[Bug] Expected identifier in struct declaration

### ISSUE THREAD

**Issue by tryconfident** [FlineDev/RemafoX#66] opened 2022-12-01 23:31 UTC
## Steps to Reproduce:

1. Installed ReMafoX
1. Followed the installation instructions
1. Attempted to build the app

## Expected Behavior:

I expected the app to build, as usual.

## Current Behavior:

Instead, the build failed with error "Expected identifier in struct declaration" on line 19 of the ReMafoX.swift file.

## Environment

<details>
<summary>Show environment details</summary>

- App Version: 1.1.1 (Build 55)
- System Version: 12.6 (Build 21G115)
- System CPU: Apple M1 Pro
- Tier: Free

</details>

**Comment by Jeehut** [comment] 2022-12-03 13:15
@tryconfident Thank you for reporting this and sorry for the late reply.

This sounds weird and I can't reproduce this. Would you mind posting the contents of/around the line Xcode is reporting an error for? And best would be if you could also provide the related Strings file key name for which ReMafoX was generating the struct. It's possible there's a bug in escaping some special characters when producing the related code, but I need more information to tell for sure.

Thank you for your help in advance!

**Comment by Jeehut** [comment] 2022-12-10 13:23
@tryconfident Here's your friendly reminder to provide more details about this issue so I can help you. 🙂

**Comment by Jeehut** [comment] 2023-01-14 09:46
I'm closing this bug report as I can't reproduce it without further information and none was provided for over a month.
If more info is provided and it was stated, that this problem still occurs, I will reopen.

**Closed by Jeehut** 2023-01-14 09:46 UTC
Labels: Bug Report, Size: Small, Needs More Information
