### ISSUE TITLE
[Bug] Deadlock while translation API key setup

### ISSUE THREAD

**Issue by NickAtGit** [FlineDev/RemafoX#59] opened 2022-11-08 03:06 UTC
## Steps to Reproduce:

1. Create a new project
2. Go to machine translate in the setup wizard 
3. Click Setup API Keys -> Click one of the linkes -> Opens Safari -> Go back to app -> API Keys window is gone and wizard window below is not clickable anymore. Wizard window looks active and is not grayed out.

## Expected Behavior:

API Key window does not disappear.

## Current Behavior:

API Key window disappears and the app ends in a deadlock. CMD-Q doesn't work anymore. Only force quit works.

## Environment

- App Version: 1.1.0 (Build 54)
- System Version: 12.5.1 (Build 21G83)
- System CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
- Tier: Max

**Comment by Jeehut** [comment] 2022-11-08 23:21
@NickAtGit Thank you for reporting this.

I am aware of some issues related to window management and dialogs. The window management issues are hard to fix due to SwiftUI lacking programmatic controls here, I really hope Apple's gonna tackle that during WWDC 2023. As for the dialog issues, I will investigate them and try to find a solution soon. I think that will help with the issue here.

For the time being, (force-)quitting and restarting the app should always work to reset all window/dialog issues.

**Comment by Jeehut** [comment] 2023-04-13 17:04
@NickAtGit I just fully reworked the window management & navigation of RemafoX (and will probably write about it on [my blog](https://fline.dev)) and can no longer reproduce this issue. The fix will ship with version `1.5.0` which will be released in a couple of days.

Thank you again for reporting this issue!

**Closed by Jeehut** 2023-04-13 17:04 UTC
Labels: Bug Report, Size: Small
