### ISSUE TITLE
[Bug] Changing Search Paths Locks UI

### ISSUE THREAD

**Issue by Sherlouk** [FlineDev/ReMafoX#37] opened 2022-10-15 13:21 UTC
## Steps to Reproduce:

1. Edit "Subpaths to Skip in Search" via Search Paths configuration
1. Notice how entire application freezes temporarily

## Expected Behavior:

The application UI should continue to usable with updates happening in the background. If the update needs to be done synchronously, then it should only update once a button is pressed and which (on press) should visibly show a progress indicator.

## Current Behavior:

The application freezes.

## Environment

<details>
<summary>Show environment details</summary>

- App Version: 1.0.2 (Build 51)
- System Version: 13.0 (Build 22A5342f)
- System CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz

</details>

**Comment by Jeehut** [comment] 2022-10-15 15:15
@Sherlouk Thank you for reporting this.

You mention "notice how entire application freezes temporarily", but I can't find a video linked where I could notice that, could it be that you forgot to upload it? A video would be really helpful.

I also noticed you're on macOS Ventura Beta, do you experience the same issue on a non-beta build? Just in case you have the chance of testing it on Monterey.

**Comment by Sherlouk** [comment] 2022-10-15 15:17
> I also noticed you're on macOS Ventura Beta, do you experience the same issue on a non-beta build? Just in case you have the chance of testing it on Monterey.

Confirmed, this bug does not appear to happen on Monterey.

**Comment by Jeehut** [comment] 2022-10-15 15:44
@Sherlouk Alright, in that case I will just mention this in #9 to make sure I don't forget to check this, too, when adding full Ventura support. But Ventura is simply not supported at the moment (it's in Beta as of the time of this writing) and therefore this is a duplicate of #9. I'm closing it.

Thank you for reporting and checking things! Note that I will work on Ventura support as soon as there's an RC of Ventura so I can install it on my main Mac and test things out and upload an app targeting Ventura to the Mac App Store.

**Closed by Jeehut** 2022-10-15 15:44 UTC
Labels: Bug Report, Size: Small
